### ISSUE TITLE
Extracting Android TV launcher activities

### ISSUE THREAD

**Issue by gshah30** [DeviceFarmer/adbkit-apkreader#12]
Hi,

Currently, the `launcherActivities` array in APKReader output contains all the activities with action **MAIN** and category **LAUNCHER**. These are the activities that can be launched on Android Mobile Devices.

I need to extract launcher activities for Android TV devices. Such activities have action **MAIN** and category **LEANBACK_LAUNCHER**.

So I am proposing to add an array named `leanbackLauncherActivities` in the output of APKReader that would contain all the Android TV launcher activities. 

This is the [PR](https://github.com/DeviceFarmer/adbkit-apkreader/pull/13), 
1. Will it be accepted as a contribution (I will follow all the rules) ?
2. If yes, how long will it take to reflect in a new release ?

Thanks.

**Comment by koral--** [comment]
ad 1. yes, of course :)
ad 2. in ~1 working day after PR gets merged
currently DCO check is failing, I'll repair semaphore CI check ASAP.

**Comment by koral--** [comment]
Done in #13
